#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      initial-size: 5
      #最小连接池数量
      min-idle: 10
      #最大连接池数量
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在连接池中最小生存时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      #配置一个连接在连接池中最大生存时间,单位是毫秒
      max-evictable-idle-time-millis: 900000
      #配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true



#    druid:
#      #主数据源
#      master:
#        url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#      #从库数据源
#      slave:
#        #从库数据源默认关闭
#        enabled: false
#        url:
#        username:
#        password:
#        #初始连接数
#      initial-size: 5
#      #最小连接池数量
#      min-idle: 10
#      #最大连接池数量
#      max-active: 20
#      #配置获取连接等待超时的时间
#      max-wait: 60000
#      #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      #配置一个连接在连接池中最小生存时间,单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      #配置一个连接在连接池中最大生存时间,单位是毫秒
#      max-evictable-idle-time-millis: 900000
#      #配置检测连接是否有效
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /monitor/druid/*
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true

